[32mINFO    [0m root:test_login_ddt.py:39 ****** Verifying login test ******
[31m[1mERROR   [0m root:test_login_ddt.py:51 ****** Login test is failed ******